[package]
name = "playlist-engine"
version.workspace = true
repository.workspace = true
edition = "2021"
license = "MIT"
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
undocumented_unsafe_blocks = "deny"
