[package]
name = "retrovert-player-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
flowi.workspace = true
log.workspace = true
retrovert-host.workspace = true

[dev-dependencies]
png = "0.17"
retrovert-player.workspace = true

[lints]
workspace = true
